version: "3.1"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - maria_db
    links:
      - maria_db:app_db
  maria_db:
    image: mariadb:10.6
    container_name: maria_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: rating_app
      MYSQL_USER: root
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: password123
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=maria_db
    depends_on:
      - maria_db