version: "3.1"
services:
  maria_db:
    image: mariadb:10.6
    container_name: maria_db
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/resources/init:/docker-entrypoint-initdb.d"
      - "./src/main/resources/db/migration:/docker-entrypoint-migration.d"
    environment:
      MYSQL_ROOT_PASSWORD: password123
  api_service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - maria_db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=maria_db
    depends_on:
      - maria_db